In [2]:
#_♥ Ders 29: Çoklu Doğrusal Regresyon Kodlaması: Veri Kümesini Hazırlama

#1.kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2.veri onisleme
#2.1.veri yukleme
veriler = pd.read_csv('veriler.csv')
#pd.read_csv("veriler.csv")
#test
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


In [3]:
#encoder: Kategorik -> Numeric
ulke = veriler.iloc[:,0:1].values
print(ulke)

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

ulke[:,0] = le.fit_transform(veriler.iloc[:,0])

print(ulke)


ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
print(ulke)

#encoder: Kategorik -> Numeric
c = veriler.iloc[:,-1:].values
print(c)


from sklearn import preprocessing

le = preprocessing.LabelEncoder()

c[:,-1] = le.fit_transform(veriler.iloc[:,-1])

print(c)


ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()
print(c)


[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[['e']
 ['e']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['k']
 ['k']]
[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 

In [4]:
boyKiloYas = veriler.iloc[:,1:4].values
print(boyKiloYas)

[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]


In [5]:
#numpy dizileri dataframe donusumu
sonuc = pd.DataFrame(data=ulke, index = range(22), columns = ['fr','tr','us'])
#print(sonuc)

sonuc2 = pd.DataFrame(data=boyKiloYas, index = range(22), columns = ['boy','kilo','yas'])
print(sonuc2)

cinsiyet = veriler.iloc[:,-1].values
print(cinsiyet)

sonuc3 = pd.DataFrame(data = c[:,0:1], index = range(22), columns = ['cinsiyet'])
print(sonuc3)


    boy  kilo  yas
0   130    30   10
1   125    36   11
2   135    34   10
3   133    30    9
4   129    38   12
5   180    90   30
6   190    80   25
7   175    90   35
8   177    60   22
9   185   105   33
10  165    55   27
11  155    50   44
12  160    58   39
13  162    59   41
14  167    62   55
15  174    70   47
16  193    90   23
17  187    80   27
18  183    88   28
19  159    40   29
20  164    66   32
21  166    56   42
['e' 'e' 'k' 'k' 'e' 'e' 'e' 'e' 'k' 'e' 'k' 'k' 'k' 'k' 'k' 'e' 'e' 'e'
 'e' 'k' 'k' 'k']
    cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0


In [6]:
#dataframe birlestirme islemi
s=pd.concat([sonuc,sonuc2], axis=1)
print(s)

s2=pd.concat([s,sonuc3], axis=1)
print(s2)


     fr   tr   us  boy  kilo  yas
0   0.0  1.0  0.0  130    30   10
1   0.0  1.0  0.0  125    36   11
2   0.0  1.0  0.0  135    34   10
3   0.0  1.0  0.0  133    30    9
4   0.0  1.0  0.0  129    38   12
5   0.0  1.0  0.0  180    90   30
6   0.0  1.0  0.0  190    80   25
7   0.0  1.0  0.0  175    90   35
8   0.0  1.0  0.0  177    60   22
9   0.0  0.0  1.0  185   105   33
10  0.0  0.0  1.0  165    55   27
11  0.0  0.0  1.0  155    50   44
12  0.0  0.0  1.0  160    58   39
13  0.0  0.0  1.0  162    59   41
14  0.0  0.0  1.0  167    62   55
15  1.0  0.0  0.0  174    70   47
16  1.0  0.0  0.0  193    90   23
17  1.0  0.0  0.0  187    80   27
18  1.0  0.0  0.0  183    88   28
19  1.0  0.0  0.0  159    40   29
20  1.0  0.0  0.0  164    66   32
21  1.0  0.0  0.0  166    56   42
     fr   tr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.

In [7]:
#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33, random_state=0)

#_♥ Ders 29: Çoklu Doğrusal Regresyon Kodlaması: Veri Kümesini Hazırlama

In [8]:
#Ders 30: Çoklu Doğrusal Regresyon Kodlaması: Regresyon Modeli

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_test)

boy = s2.iloc[:,3:4].values
print(boy)
sol = s2.iloc[:,:3]
sag = s2.iloc[:,4:]

veri = pd.concat([sol,sag],axis=1)

x_train, x_test,y_train,y_test = train_test_split(veri,boy,test_size=0.33, random_state=0)


r2 = LinearRegression()
r2.fit(x_train,y_train)

y_pred = r2.predict(x_test)

veri

[[130]
 [125]
 [135]
 [133]
 [129]
 [180]
 [190]
 [175]
 [177]
 [185]
 [165]
 [155]
 [160]
 [162]
 [167]
 [174]
 [193]
 [187]
 [183]
 [159]
 [164]
 [166]]


fr   tr   us  kilo  yas  cinsiyet
0   0.0  1.0  0.0    30   10       1.0
1   0.0  1.0  0.0    36   11       1.0
2   0.0  1.0  0.0    34   10       0.0
3   0.0  1.0  0.0    30    9       0.0
4   0.0  1.0  0.0    38   12       1.0
5   0.0  1.0  0.0    90   30       1.0
6   0.0  1.0  0.0    80   25       1.0
7   0.0  1.0  0.0    90   35       1.0
8   0.0  1.0  0.0    60   22       0.0
9   0.0  0.0  1.0   105   33       1.0
10  0.0  0.0  1.0    55   27       0.0
11  0.0  0.0  1.0    50   44       0.0
12  0.0  0.0  1.0    58   39       0.0
13  0.0  0.0  1.0    59   41       0.0
14  0.0  0.0  1.0    62   55       0.0
15  1.0  0.0  0.0    70   47       1.0
16  1.0  0.0  0.0    90   23       1.0
17  1.0  0.0  0.0    80   27       1.0
18  1.0  0.0  0.0    88   28       1.0
19  1.0  0.0  0.0    40   29       0.0
20  1.0  0.0  0.0    66   32       0.0
21  1.0  0.0  0.0    56   42       0.0

In [15]:
#Ders 31: Geri Eleme Yöntemi (Backward Elimination

import statsmodels.api as sm

X = np.append(arr = np.ones((22,1)).astype(int), values=veri, axis=1)

X_l = veri.iloc[:,[0,1,2,3,4,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(boy,X_l).fit()
print(model.summary())
#print(X)

X_l = veri.iloc[:,[0,1,2,3,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(boy,X_l).fit()
print(model.summary())



X_l = veri.iloc[:,[0,1,2,3]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(boy,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Sun, 05 Nov 2023   Prob (F-statistic):           5.41e-07
Time:                        17:34:10   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.0

In [ ]:
#linear regression
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X,Y)

print('Linear OLS')
model=sm.OLS(lin_reg.predict(X),X)
print(model.fit().summary())

print('Linear R2 degeri')
print(r2_score(Y, lin_reg.predict(X)))


#polynomial regression

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
x_poly = poly_reg.fit_transform(X)
print(x_poly)
lin_reg2 = LinearRegression()
lin_reg2.fit(x_poly,y)


#tahminler


print('poly OLS')
model2=sm.OLS(lin_reg2.predict(poly_reg.fit_transform(X)),X)
print(model2.fit().summary())

print('Polynomial R2 degeri')
print(r2_score(Y, lin_reg2.predict(poly_reg.fit_transform(X))))

#verilerin olceklenmesi
from sklearn.preprocessing import StandardScaler

sc1=StandardScaler()
x_olcekli = sc1.fit_transform(X)
sc2=StandardScaler()
y_olcekli = np.ravel(sc2.fit_transform(Y.reshape(-1,1)))


from sklearn.svm import SVR

svr_reg = SVR(kernel='rbf')
svr_reg.fit(x_olcekli,y_olcekli)


print('SVR OLS')
model3=sm.OLS(svr_reg.predict(x_olcekli),x_olcekli)
print(model3.fit().summary())


print('SVR R2 degeri')
print(r2_score(y_olcekli, svr_reg.predict(x_olcekli)))

#Decision Tree Regresyon
from sklearn.tree import DecisionTreeRegressor
r_dt = DecisionTreeRegressor(random_state=0)
r_dt.fit(X,Y)


print('Decision Tree OLS')
model4=sm.OLS(r_dt.predict(X),X)
print(model4.fit().summary())

print('Decision Tree R2 degeri')
print(r2_score(Y, r_dt.predict(X)))

#Random Forest Regresyonu
from sklearn.ensemble import RandomForestRegressor
rf_reg=RandomForestRegressor(n_estimators = 10,random_state=0)
rf_reg.fit(X,Y.ravel())



print('Random Forest OLS')
model5=sm.OLS(rf_reg.predict(X),X)
print(model5.fit().summary())



print('Random Forest R2 degeri')
print(r2_score(Y, rf_reg.predict(X)))